version: '3'
services:
    node:
        build:
            .
        volumes:
            - "./:/usr/local/app"
        working_dir: "/usr/local/app"
        command: "npm run install_run"
        environment:
            LANG: "zh_CN.UTF-8"
            LC_ALL: "zh_CN.UTF-8"
        depends_on:
          - nginx
          - postgres
          - redis

    nginx:
        build:
            ./etc/nginx
        volumes:
            - "./etc/nginx:/etc/nginx"
        ports:
            - "80:80"
            - "443:443"
        environment:
            LANG: "zh_CN.UTF-8"
            LC_ALL: "zh_CN.UTF-8"
        restart: always

    postgres:
        build:
            ./etc/postgresql
        volumes:
            - "./etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_PASSWORD: "lzw981018"
            LANG: "zh_CN.UTF-8"
            LC_ALL: "zh_CN.UTF-8"
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        restart: always

    redis:
        image: "redis:5.0.7-alpine"
        volumes:
            - "./etc/redis:/etc/redis"
        ports:
            - "127.0.0.1:6379:6379"
        command: redis-server /etc/redis/redis.conf
        restart: always

