version: '3'
services:

    nginx:
        image: "nginx:1.17.8"
        volumes:
            - "./etc/nginx:/etc/nginx"
        ports:
            - "80:80"
            - "443:443"
        restart: always

    mysql:
        image: "mysql:8.0.19"
        volumes:
            - "./etc/mysql:/etc/mysql"
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "lzw981018"
        restart: always

    redis:
        image: "redis:5.0.7"
        volumes:
            - "./etc/redis:/etc/redis"
        ports:
            - "127.0.0.1:6379:6379"
        command: redis-server /etc/redis/redis.conf
        restart: always

